  - name: Install mysql library
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: install mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: Start and enable mysqk-server services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.bsdaws82s.site

    register: mysql_info
    ignore_errors: true

  - name: print the mysql info output
    ansible.builtin.debug:
      msg: "MySql Info: {{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
    when: mysql_info.failed is true