- name: remove existing directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"              # backend folder is /app and frontend folder is /usr/share/nginx/html
    state: absent


- name: create app directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"              
    state: directory

- name: download the code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCATION }}" 
    remote_src: yes